public enum WeaponTraitType
{
    WEAPONTRAIT_LIGHT = 0,
    WEAPONTRAIT_HEAVY,
    WEAPONTRAIT_TWOHANDED,
    WEAPONTRAIT_VERSATILE,
    WEAPONTRAIT_AMMUNITION,
    WEAPONTRAIT_RANGED,
    WEAPONTRAIT_THROWN,
    //INVALID
    WEAPONTRAIT_INVALID = -1,
}
