public enum PathfindingTerrainType
{
    NORMAL_TERRAIN = 0,
    DIFFICULT_TERRAIN,
    GREATER_DIFFICULT_TERRAIN,
    HAZARDOUS_TERRAIN,
    NARROW_TERRAIN,
    UNEVEN_TERRAIN,
    INCLINED_TERRAIN,
    INVALID_TERRAIN
}
