public enum CinematicSubstate
{
    CINEMATICSUBSTATE_START = 0,
    CINEMATICSUBSTATE_INPROGRESS,
    CINEMATICSUBSTATE_END,
    CINEMATICSUBSTATE_NONE,
    CINEMATICSUBSTATE_COUNT,
    CINEMATICSUBSTATE_INVALID = -1,
}
