public enum DashingSubstate
{
    DASHINGSUBSTATE_START = 0,
    DASHINGSUBSTATE_INPROGRESS,
    DASHINGSUBSTATE_END,
    DASHINGSUBSTATE_NONE,
    DASHINGSUBSTATE_COUNT,
    DASHINGSUBSTATE_INVALID = -1,
}
