public enum InteractingSubstate
{
    INTERACTINGSUBSTATE_DIALOGUE = 0,
    INTERACTINGSUBSTATE_PICKUP,
    INTERACTINGSUBSTATE_BUTTON,
    INTERACTINGSUBSTATE_NONE,
    INTERACTINGSUBSTATE_COUNT,
    INTERACTINGSUBSTATE_INVALID = -1,
}
