public enum PrimaryState
{
    PRIMARYSTATE_IDLE = 0,
    //PRIMARYSTATE_STATIONARY,
    PRIMARYSTATE_LOCKED,
    PRIMARYSTATE_WALKING,
    PRIMARYSTATE_LOITERING,
    PRIMARYSTATE_DEAD,
    PRIMARYSTATE_COUNT,
    PRIMARYSTATE_INVALID = -1,
}
