public enum SecondaryState
{
    SECONDARYSTATE_NONE = 0,
    SECONDARYSTATE_INTERACTING,
    SECONDARYSTATE_DASHING,
    SECONDARYSTATE_THROWING,
    SECONDARYSTATE_ATTACKING,
    SECONDARYSTATE_CINEMATIC,
    SECONDARYSTATE_PAUSEMENU,
    SECONDARYSTATE_COUNT,
    SECONDARYSTATE_INVALID = -1,
}
